version: 2.1
orbs:
  python: circleci/python@2
  evals: circleci/evals@2.0
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11-node
    working_directory: ~/project/python/agents/RAG
    steps:
      - checkout:
          path: ~/project
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run dummy tests
          command: |
            echo "Running dummy test 1"
            echo "Test 1 passed"
            echo "Running dummy test 2"
            echo "Test 2 passed"
            poetry run pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not
            find any tests to run.')
      - store_test_results:
          path: junit.xml
  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: "#e.g. ./deploy.sh"
  evals-test-assertions-job:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - evals/test:
          assertions: assertions.json
          metrics: eval_results.json
          results: test_results.xml
workflows:
  build-and-test:
    jobs:
      - test-python:
          context:
            - Gemini-metapics
            - Weaviate-adkagents
            - Supabase-context
            - LangSmith-context
  test-eval-workflow:
    jobs:
      - evals-test-assertions-job
